@startuml create15
title "Anotar Bolo 15 fatias"
start
:Escolher massa;
if (Massa Red Velvet) then (sim)
  #F5B7B1:adicional de 10.00;
else (não)
endif
:Escolher até 2 recheios;
if (Algum dos recheios é pistache) then (sim)
  #F5B7B1:adicional de 14.00;
else (não)
endif
:Escolher até 2 adicionais;
if (Tem adicional) then (sim)
  #F5B7B1:adicional de 15.00;
  if (Tem segundo adicional) then (sim)
    #F5B7B1:adicional de 15.00;
  else (não)
  endif
else (não)
endif
:Preço final é calculado e exibido;
@enduml